services:
  # 1. Database (MySQL)
  db:
    image: mysql:8.0
    container_name: raptika_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_raptika
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - raptika_network

  # 2. PHP-FPM Service (Laravel backend)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raptika_backend
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - raptika_network

  # 3. Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: raptika_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - raptika_network

volumes:
  db_data:

networks:
  raptika_network:
    driver: bridge
   